[build]
publish = "public"
command = "hugo --gc --minify -s Hugo/beef-lang.org"

[context.production.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo -s Hugo/beef-lang.org"

[context.split1.environment]
HUGO_VERSION = "0.52"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL -s Hugo/beef-lang.org"

[context.deploy-preview.environment]
HUGO_VERSION = "0.52"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL -s Hugo/beef-lang.org"

[context.branch-deploy.environment]
HUGO_VERSION = "0.52"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
